### ISSUE TITLE
All strings in app should be kept in translation files

### ISSUE THREAD

**Issue by buren** [justarrived/p2p-client#3]
cc @tikkat

**Comment by ClickoBito** [comment]
Someone should be looking into how this is done with react native this week.

**Comment by tikkat** [comment]
Great input @buren, this is great for you in the project group to prepare for from the beginning. I18n is (and if not; should be) used in every serious software project. After 2 secs of Googling I found this: https://github.com/stefalda/ReactNativeLocalization

Looks alright, feel free to choose a better way of handling it if you find anything better :) Please keep me updated in that case, I'm curious how to best handle i18n in react native too! @HeyHoProBro

**Comment by buren** [comment]
@filipchr what are you using over at Welcome? :)

**Comment by filipchr** [comment]
@buren!
We are using this [react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n).
We are using this structure
```
├ SE
|   ├ en.json
|   ├ sv.json
├ NO
|   ├ en.json
|   ├ no.json
```
where SE and NO are the users current country and the json files are the translations.
