### ISSUE TITLE
Create .eslint file for code style consistency

### ISSUE THREAD

**Issue by buren** [justarrived/p2p-client#9]

**Comment by ckarlss0n** [comment]
Great idea, @buren!

I've experimented with different configurations for a while now, and it seems to be a very helpful tool!
Do you have any suggestions on what to include in the .eslintrc?

A popular way of doing it seems to be to extend [`eslint-config-airbnb`](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb), which includes [`eslint`](https://www.npmjs.com/package/eslint), [`eslint-plugin-import`](https://www.npmjs.com/package/eslint-plugin-import), [`eslint-plugin-react`](https://www.npmjs.com/package/eslint-plugin-react), and [`eslint-plugin-jsx-a11y`](https://www.npmjs.com/package/eslint-plugin-jsx-a11y). Maybe we could do that and combine it with [`eslint-plugin-react-native`](https://github.com/Intellicode/eslint-plugin-react-native). Or do you think we should make our own configuration from scratch?

Even though I haven't looked at every single setting in the Airbnb configuration yet, I've tried this setup on the (little) code that is in the repository right now (using Atom with linter and linter-eslint), and it seems to work fine and give good feedback!

Do you have any feedback on the configuration I'm using right now? Thanks!

```json
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb",
    "plugin:react-native/all"
  ],
  "plugins": [
    "react-native"
  ],
  "rules": {
    "react/jsx-filename-extension": [
      "error",
      {
        "extensions": [
          ".js",
          ".jsx",
          ".android.js",
          ".ios.js"
        ]
      }
    ]
  }
}
  ```

**Comment by buren** [comment]
Airbnbs guide is widely used by and is, in my opinion, sensible. 

:+1: for the config you posted @ckarlss0n

**Comment by ckarlss0n** [comment]
The ESLint configuration file has now been added (see pull request #10), and the changes have been merged to the develop branch.

Thanks for the feedback, @buren! :rocket:
